name: ml
channels:
  - conda-forge
  - defaults
dependencies:
  - _py-xgboost-mutex=2.0
  - backcall=0.1.0
  - blas=1.0
  - bleach=3.1.0
  - ca-certificates=2018.11.29
  - certifi=2018.11.29
  - cycler=0.10.0
  - dbus=1.13.6
  - decorator=4.3.2
  - entrypoints=0.3
  - expat=2.2.6
  - fontconfig=2.13.0
  - freetype=2.9.1
  - glib=2.56.2
  - gmp=6.1.2
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - icu=58.2
  - intel-openmp=2019.1
  - ipykernel=5.1.0
  - ipython=7.3.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.4.2
  - jedi=0.13.3
  - jinja2=2.10
  - jpeg=9b
  - jsonschema=2.6.0
  - jupyter=1.0.0
  - jupyter_client=5.2.4
  - jupyter_console=6.0.0
  - jupyter_core=4.4.0
  - kiwisolver=1.0.1
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libpng=1.6.36
  - libsodium=1.0.16
  - libuuid=1.0.3
  - libxcb=1.13
  - libxgboost=0.81
  - libxml2=2.9.9
  - markupsafe=1.1.1
  - matplotlib=3.0.2
  - mistune=0.8.4
  - mkl=2019.1
  - mkl_fft=1.0.10
  - mkl_random=1.0.2
  - nbconvert=5.3.1
  - nbformat=4.4.0
  - ncurses=6.1
  - notebook=5.7.4
  - numpy=1.16.2
  - numpy-base=1.16.2
  - openssl=1.1.1b
  - pandas=0.24.1
  - pandoc=2.2.3.2
  - pandocfilters=1.4.2
  - parso=0.3.4
  - pcre=8.42
  - pexpect=4.6.0
  - pickleshare=0.7.5
  - pip=19.0.3
  - prometheus_client=0.6.0
  - prompt_toolkit=2.0.9
  - ptyprocess=0.6.0
  - py-xgboost=0.81
  - pygments=2.3.1
  - pyparsing=2.3.1
  - pyqt=5.9.2
  - python=3.7.2
  - python-dateutil=2.8.0
  - pytz=2018.9
  - pyzmq=18.0.0
  - qt=5.9.7
  - qtconsole=4.4.3
  - readline=7.0
  - scikit-learn=0.20.2
  - scipy=1.2.1
  - send2trash=1.5.0
  - setuptools=40.8.0
  - sip=4.19.8
  - six=1.12.0
  - sqlite=3.26.0
  - terminado=0.8.1
  - testpath=0.4.2
  - tk=8.6.8
  - tornado=5.1.1
  - traitlets=4.3.2
  - wcwidth=0.1.7
  - webencodings=0.5.1
  - wheel=0.33.1
  - widgetsnbextension=3.4.2
  - xgboost=0.81
  - xz=5.2.4
  - zeromq=4.3.1
  - zlib=1.2.11

